apiVersion: v2
name: savannah-backend
description: A Helm chart for Savannah Backend API
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "12.1.9"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "17.3.7"  
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

keywords:
  - api
  - backend
  - golang
  - gin
  - postgresql
  - redis

maintainers:
  - name: "Backend Team"
    email: "backend@savannah.com"

sources:
  - https://github.com/jmukavana/savannah-backend
